### ISSUE TITLE
Not able to flash when using GCC

### ISSUE THREAD

**Issue by VVESTM** [ARM-software/vscode-embedded-debug#13]
Type: Bug Report

Wrong file is selected when working with GCC
- OS and Version: Windows
- VS Code Version: 1.75.1
- Extension Version: v0.8.0
- Target Device: STM32 NUCLEO-U575ZI-Q

- I am able to compile with GCC but when flashing and debugging, wrong file is selected (.axf instead of .elf)

**To Reproduce**
1. Go to 'CMSIS extension', select the .csolution.yml file
2. Select "Build Type" GCC
3. Build, this generates the .elf
5. Flash. In this case, I have an error because it is looking for .axf instead of .elf.

For information, here is my task.json:
![image](https://user-images.githubusercontent.com/22098252/221226571-c3d79787-cc44-4da5-bba0-3b66f178257b.png)
Then, in settings, I have:
![image](https://user-images.githubusercontent.com/22098252/221226731-9fed2f7c-2710-494a-8e2c-8083a3a43f1f.png)
So, seems .elf is supported.
(With AC6, I am able to compile, flash and debug with same settings)

Thanks for your help

**Comment by thegecko** [comment]
The `getApplicationFile` command used in your task defers to the `cmsis` extension when that's installed (which looks to be the case) and the `Application Pattern` is ignored.

@mcgordonite Can you confirm whether the `cmsis-csolution.getBinaryFile` command returns an `axf` file when using gcc? It may need to return a different path.

In the meantime, this can be worked around by using the full file path to your binary file in the task and not using the command.

**Comment by VVESTM** [comment]
Thanks, yes, I am not blocked as I can use the full path (already tested and working). 
But in order to share a single task.json file between several projects, the getBinaryFile would be more convenient.

Can also be linked to https://github.com/ARM-software/vscode-cmsis-csolution/issues/20.

**Comment by thegecko** [comment]
@mcgordonite could you confirm if this should work?

**Comment by mcgordonite** [comment]
This should now work: the binary file path is determined dynamically based on the generated cbuild.yml file. You should now be able to call your binary whatever you like.

See https://github.com/ARM-software/vscode-cmsis-csolution/issues/20.

**Comment by VVESTM** [comment]
close by  https://github.com/ARM-software/vscode-cmsis-csolution/issues/20
