### ISSUE TITLE
Is there any possible to add an options that can set debugger's speed

### ISSUE THREAD

**Issue by sin1111yi** [ARM-software/vscode-embedded-debug#14]
Debugger's speed(freq, whatever) is an usual option for debugging. There is an option named _dbgconf_ in tasks.json, but i don't how can I write one, or maybe it can be generated by MDK? Whatever, add Debugger's speed as an options in tasks and launch can be useful, thanks!

**Comment by microbit-carlos** [comment]
Yes, this would be a welcome addition.
