### ISSUE TITLE
Support flashing of Intel Hex programmes

### ISSUE THREAD

**Issue by microbit-carlos** [ARM-software/vscode-embedded-debug#15]
Type: Feature Request

Pointing to an Intel Hex file as the `program` in `tasks.json` shows this error:
```
Not an ELF file: invalid magic number
Flash failed
```
So I guess it only ELF files are currently support?

It'd be great if flashing Intel Hex files could be supported as well.

**Comment by thegecko** [comment]
@microbit-carlos can you try the `embedded-debug.daplink-flash` task type for your use case instead?

You may also be able to right-click the hex file in your workspace and flash it directly if you are using the `arm.device-manager` extension and have a DAPLink device selected.

**Comment by microbit-carlos** [comment]
Thanks Rob, that worked! 🎉

In case it helps other people, this is my tasks.json that I've used with GH CodeSpaces, this extension, and WebUSB via micro:bit V2 DAPLink:


```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "embedded-debug.daplink-flash",
			"serialNumber": "${command:device-manager.getSerialNumber}",
			"program": "/workspaces/microbit-v2-samples/MICROBIT.hex",
			"problemMatcher": [],
			"label": "embedded-debug.daplink-flash: Flash Device",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

Will there be more info about the `embedded-debug.daplink-flash` task type in the README?

**Comment by thegecko** [comment]
@Elise-Kaminski we need to outline this flash type in the docs for DAPLink devices.

For completeness, the `daplink-flash` task can be added through the VS Code task templating system and should work on vscode.dev/github.dev as well as codespaces.
