### ISSUE TITLE
Readme.md link error

### ISSUE THREAD

**Issue by daldr-ntml** [ARM-software/vscode-embedded-debug#18]
In section 'Debug your project' this link has a spelling error and doesn't work.

https://github.com/ARM-software/vscode-embedded-debug#debug-configurattion-options

Also, the bullet numbers in that section are not sequential.

**Comment by thegecko** [comment]
Thanks @DavidA2014 

cc @Elise-Kaminski

**Comment by thegecko** [comment]
Thanks!
