### ISSUE TITLE
the axf should be generated with debug information regardless of the target

### ISSUE THREAD

**Issue by fredo514** [ARM-software/vscode-embedded-debug#4]
Type: Feature Request

This maybe be already possible through a way I'm not aware, but it would be nice that since the build command generates a .axf file automatically anyway, it contained the debug information by default without needing to specifically compile in for debug.

**Comment by thegecko** [comment]
@fredo514 the build functionality is supported in the `cmsis-csolution` extension. Would you mind recreating this request over at:

https://github.com/ARM-software/vscode-cmsis-csolution/issues
