### ISSUE TITLE
Path error when debugger tries to open source file in Codespaces

### ISSUE THREAD

**Issue by riestmo** [ARM-software/vscode-embedded-debug#9]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.74.3
- Extension Version: v0.6.2
- Target Device: CY8C624ABZI-S2D44:Cortex-M4

When starting a debug session in Github Codespaces, the debugger starts successfully and runs to main using the default setting for "debugFrom". However, it fails to open the main.c file as shown below.

![image](https://user-images.githubusercontent.com/75073361/213166070-db639951-cd87-4b0d-951d-e62f8986f5d5.png)

I suspect it's a similar scheme issue as discussed in https://github.com/ARM-software/vscode-embedded-debug/issues/7#issuecomment-1383865800

**Expected behavior**
The debugger opens the C file once a breakpoint is hit.

**Comment by thegecko** [comment]
I'll investigate.

Out of interest, are you building the binary in the codespace or somewhere else?

**Comment by riestmo** [comment]
I'm building it in the Codespace.

**Comment by thegecko** [comment]
This is very frustrating. I think it's a bug in codespaces and github.dev regarding their file schemes.

This used to work, so is a recent regression. I'll need to create a reproducer and file an issue with GitHub

**Comment by thegecko** [comment]
Raised here:

https://github.com/orgs/community/discussions/44904
https://github.com/microsoft/vscode/issues/171991

**Comment by riestmo** [comment]
Thanks for raising this issue!

**Comment by thegecko** [comment]
@riestmo We've released an update to the debug extension this morning which could fix this issue.

Could you confirm if you see any improvement?

**Comment by riestmo** [comment]
Thanks for the update @thegecko ! I can confirm that the issue is fixed with the latest release v0.9.0.

**Comment by thegecko** [comment]
Nice! Sorry about the delay
